import localFont from "next/font/local";
import "./globals.css";
import { ToastContainer } from "react-toastify";

const myFont = localFont({
  src: "../../public/fonts/IRANYekanMobileFN Medium.ttf",
  display: "swap",
});
export const metadata = {
  title: "reservation platform",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${myFont.className}`}>
        {children}
        <ToastContainer />
      </body>
    </html>
  );
  
}
